### ISSUE TITLE
Live demo video link

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/flashtype#4]
The link seems to be broken for the video in docs_images/FlashType.avi

**Comment by rohan-kulkarni-25** [comment]
Hey I will like to work on it !

**Comment by rohank2502** [comment]
Hey I will like to work on it !

**Comment by rohank2502** [comment]
Hey I will like to work on it !

**Comment by kaiwalyakoparkar** [comment]
Sure go ahead. I'll assign it to you

**Comment by rohan-kulkarni-25** [comment]
Will like to know exactly what I have to do ? I saw that video I have downloaded it too !! Should I Delete the  first one and upload again and copy the link or just once again copy the link and just paste it !!

**Comment by kaiwalyakoparkar** [comment]
Actually I have to embed that video in readme file under live demo heading. You will have to fix the link in the readme that will enable the video to run in readme.

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Actually I have to embed that video in readme file under live demo heading. You will have to fix the link in the readme that will enable the video to run in readme.

Ook !!!

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Actually I have to embed that video in readme file under live demo heading. You will have to fix the link in the readme that will enable the video to run in readme.

But its still showing that when we click the link it redirect to the path of the video and when we say view raw it shows the video !

**Comment by kaiwalyakoparkar** [comment]
You can convert it into .gif format and then embed I guess

**Comment by kaiwalyakoparkar** [comment]
Do you need any help?

**Comment by vikasganiga05** [comment]
Hi, I will like to work on this issue.

**Comment by rohan-kulkarni-25** [comment]
Ok Assign him this issue I am not getting what u are saying

**Comment by kaiwalyakoparkar** [comment]
Hi @vikasganiga05 ,Go for it. If you have any doubt ask me

**Comment by Salonee-Jain** [comment]
Hey! would like to work on this issue.

**Comment by kaiwalyakoparkar** [comment]
@Salonijain1248 Go for it... Convert the present video into gif and then add it to the readme...☺️

**Comment by vikasganiga05** [comment]
Hi @kaiwalyakoparkar , I fixed the issue. I converted `FlashType.avi` to `FlashType.gif`, So can i delete the `FlashType.avi` file. Then the path to the `FlashType.gif` file is a relative path.

**Comment by kaiwalyakoparkar** [comment]
@vikasganiga05 yes please delete it

**Comment by vikasganiga05** [comment]
> @vikasganiga05 yes please delete it

I deleted and opened a pull request #10

**Comment by kaiwalyakoparkar** [comment]
There are more awesome issues on Data-Structure-And-Algorithm-Interview-Kit you can head over to that repository on my account to get more green squares...☺️

**Comment by vikasganiga05** [comment]
Thank You, I will look into that. :slightly_smiling_face:
