### ISSUE TITLE
Update the readme for new contributors

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/flashtype#7]
**Is your feature request related to a problem? Please describe.**

I have recently added Contributing. md and Code-of-conduct. md files in my project. The links should be added in readme to redirect them to the files before they contribute to the project

**Describe the solution you'd like**

The links should be added in readme to redirect them to the files before they contribute to the project

**Comment by shikharcodes** [comment]
Hey @kaiwalyakoparkar, I would like to add this.

**Comment by kaiwalyakoparkar** [comment]
Sure go for it. I'll assign it to you.

**Comment by kaiwalyakoparkar** [comment]
Thanks for working on it @shikharcodes
